---
- when: module_state != 'absent'
  block:
    - name: Bastion SecGrp
      os_security_group:
        state: "{{ module_state }}"
        name: "{{ security_group }}"
        description: Security group for the bastion host

    - name: Bastion SecGrp ICMP Rule
      os_security_group_rule:
        security_group: "{{ security_group }}"
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

    - name: Bastion SecGrp SSH Rule
      os_security_group_rule:
        security_group: "{{ security_group }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

- when: module_state == 'absent'
  block:
    - name: Delete Bastion SecGrp
      os_security_group:
        state: "{{ module_state }}"
        name: "{{ security_group }}"
        description: Security group for the bastion host
