---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family|lower }}.yaml"
  when: ansible_os_family == 'RedHat'

- include_tasks: "{{ task }}.yaml"
  loop_control:
    loop_var: task
  with_items: "{{ lamp_task_manager }}"
